comment from sakakibara
PlusF/PulseLaserSystem_kivy pull request #1
Opened 2023-05-18 11:53 UTC by sakaki-bara

ZaberController.pyについて接続したアクチュエータを動かすことができたので，コードのひな型としてpushしました．今後ここに適宜変更を加えていきます．
現時点で以下の変更を予定してます．
・asyncを用いた処理
・absolute relativeの座標を引数で受け渡しするように
・stop関数は3種類
・Debugモードの追加

2023-05-18 12:19 UTC, PlusF requested changes
他の人が見えるようにしたいので、早めに直してマージしたい点を【至急】としておきました！
優先順位をつけつつ対応をお願いします🙇

2023-05-18 12:19 UTC, PlusF commented on ZaberController.py
> +        self.port = 'COM3' #check
COMポート数はハードコードせず、initの引数で受け取る
デバッグモードもinitの引数で受け取る？未定

2023-05-18 12:19 UTC, PlusF commented on ZaberController.py
> +        print('position before moving')
【至急】
以下のテストコードはinitではないところに書いてください。
def test_(機能):
  z = ZaberController()
  z.move_なんとか
  pos = z.get_position()
  posが予想通りか確かめる
みたいなコードです！

2023-05-18 12:19 UTC, PlusF commented on ZaberController.py
> +        self.vel = 1000
【至急】
先ほども伝えた通り、関数の引数で速度や位置を指定するような設計にしましょう

2023-05-18 12:19 UTC, PlusF commented on ZaberController.py
>          pass
先ほども言った通り、passは消してしまって構いません。

2023-05-18 12:19 UTC, PlusF commented on ZaberController.py
> +        self.device_x.move_absolute(self.x_absolute_position, unit=self.unit_pos)
absolute, relative等、座標指定で駆動する場合は機械限界値を超えないか事前にチェックしましょう
超える場合はreturn False
実行しても良い場合はreturn True
として、エラーハンドリングはmain.py側で行うように設計しましょうか。

2023-05-18 12:19 UTC, PlusF commented on ZaberController.py
> +    def stop(self):
【至急】
stopはx, y, 両方の3種類作りましょう

2023-05-18 12:19 UTC, PlusF commented on ZaberController.py
> +
【至急】
get_position()関数も作っておきましょう
x, y, 両方の3種類あっても良いでしょう

2023-05-18 12:19 UTC, PlusF commented on ZaberController.py
> +
def quit(self):
  self.connection.close()
みたいなのも作りましょう
mainから呼ぶのを忘れないようにしないと・・・

2023-06-12 04:33 UTC, PlusF commented on ZaberController.py
> +PORT_NUM = 3 #check
main関数でしか使わないのであれば，main関数内でのローカル変数にしましょう
（グローバル変数はバグの元なので，スコープ（変数が見える範囲）は最小限にするのが基本です．
今回はシビアなケースではないですが）

2023-06-12 04:35 UTC, PlusF commented on ZaberController.py
> +        self.port = "COM" + str(port)
portはそのまま`self.port=port`でよいです．

2023-06-12 04:40 UTC, PlusF commented on ZaberController.py
> +    async def move_absolute(self, position_x, position_y):
関数名は`move_absolute_async`にしないといけないのでは？
下の`move_default`でそのように呼び出しているので

2023-06-12 04:42 UTC, PlusF commented on ZaberController.py
> +        return position_list
```
x = self.get_position_x()
y = self.get_position_y()
return [x, y]
```
とすると簡潔に書けますね

2023-06-12 04:43 UTC, PlusF commented on ZaberController.py
> +        self.device_y.stop(unit=self.unit_pos)
こちらもせっかく定義しているので
```
self.stop_x()
self.stop_y()
```
としましょう
同じコードを複数回書くことを避ける，というのもプログラミングの原則です

2023-06-12 04:45 UTC, PlusF commented on ZaberController.py
> +    async def test(self):
test関数はクラスの外に出しましょう．
また，やらなくてもよいですが各機能ごとにtest関数を用意するとよいです．
```
def test_move_right():
def test_stop():
```
みたいな感じです
まあ，やらなくてもよいです

2023-06-12 04:46 UTC, PlusF commented on ZaberController.py
> +        self.device_x.stop(unir=self.unit.pos)
typoです．
PyCharmって予期しない引数があると警告出してくれませんでしたっけ？
stop_yも同様です

2023-06-12 04:47 UTC, PlusF reviewed
微修正をお願いします．
時間はかからないと思います

2023-06-12 05:55 UTC, sakaki-bara commented on ZaberController.py
> +        self.port = "COM" + str(port)
port番号って"COM3"ではなくて"3"(数字だけ)でも認識されるんでしょうか？

2023-06-12 05:57 UTC, sakaki-bara commented on ZaberController.py
> +    async def move_absolute(self, position_x, position_y):
関数名はmove_avsolute_asyncではなくmove_absoluteで統一しました．修正漏れでした．

2023-06-12 06:18 UTC, PlusF commented on ZaberController.py
> +        self.port = "COM" + str(port)
試したことはないですが，"3"だけでは認識しないと思います．
main.py側で"COM3"と入れてあげる予定です．
今回はどっちでもよいのですが，ポート名が"COM"で始まらないケース(OSがWindowsじゃない場合等）も存在するので一応そのような仕様にしました
重要度は全然高くないです，もはや好みですね

2023-06-12 07:08 UTC, merged