S nishida
PlusF/PulseLaserSystem_kivy pull request #2
Opened 2023-06-08 01:27 UTC by penguin-web

基本的なボタン類を配置しました

2023-06-11 23:18 UTC, PlusF commented on main.kv
> +                            freq_slider.value = self.text
テキストの数値のvalidationをmain.py内で行うようにしましょうか
現状だと，テキストの値がスライダーの範囲を超えていてもその値を設定できてしまいます．
適当にroot.check_freq(self.text)みたいに書いていただければと思います．

2023-06-11 23:25 UTC, PlusF commented on main.kv
> +                        on_value:
sliderを使いたい状況を想像したとき，「マウスのみで値を操作したい」という動機があると思います．
16~10000の値をsliderで指定できてしまうと，狙った値にすることは難しいでしょう．
sliderの範囲は例えば1~7にしてしまって，
1: 16 Hz
2: 50 Hz
3: 100 Hz
4: 500 Hz
5: 1000 Hz
6: 5000 Hz
7: 10000 Hz
のように離散的にすると

- 適当な値にサッと設定したいときはslider

- 特定の値に設定したいときはtext_input

という使い分けができると思います．
on_valueにはroot.set_freq_from_slider(self.value)のようにして，細かい内容はmain.pyに任せるようにしましょうか

2023-06-11 23:27 UTC, PlusF commented on main.kv
> +                        on_value:
speedについてもfreqと同様にお願いします

2023-06-11 23:29 UTC, PlusF commented on main.kv
> +                                root.check("auto")
そこまで大きな違いは現れませんが，処理はon_releaseのときに実行するようにしましょうか

2023-06-11 23:30 UTC, PlusF commented on main.kv
> +                            on_release:
こちらもon_releaseでお願いします

2023-06-11 23:37 UTC, PlusF commented on main.kv
> +                                    source: "source/left.png"
矢印の画像も用意してくれてありがとうございます．
めちゃくちゃ細かい要望で申し訳ないのですが，矢印の棒の部分は短いほうが可視性が上がるかなと思いました．
なんなら三角形でもよいくらいかなと（ゲームのコントローラーのイメージを持っています）

余裕があれば対応お願いします．

2023-06-11 23:41 UTC, PlusF commented on main.kv
> +                                on_release:
各移動ボタンはon_releaseでroot.stop_moving()を呼ぶ仕様にお願いします．
main.pyにない関数は適宜追加していただいて結構です．

2023-06-11 23:42 UTC, PlusF commented on main.kv
> +                                on_press:
ここもroot.start_program()のような関数を呼び出すようにお願いします．

2023-06-11 23:45 UTC, PlusF commented on main.kv
> +                    text:"Quit"
kivyでアプリを作るときはQUITボタンはなくて大丈夫です（tkinterの仕様上，仕方なく作っていたものです）
機器との通信を正常に終わらせるために用意していましたが，kivyならmain.pyに適切な処理を書けば実現できます．

2023-06-11 23:46 UTC, PlusF commented on main.py
これは`
if __name__ == '__main__':`
の中に書いても大丈夫ですかね？

2023-06-11 23:47 UTC, PlusF requested changes
リッチな機能まで対応してくれて本当に助かります．
いくつかコメントをしたので対応をお願いします。

2023-06-13 07:02 UTC, penguin-web commented on main.kv
> +                                root.check("auto")
ここでは，ON/OFFの状態を固定できるToggle Button というものを使っています．なのでここで言うon_pressは単純にONにした際に実行する処理を示しています．

2023-06-13 07:03 UTC, penguin-web commented on main.kv
> +                        on_value:
なるほど！！！確かにそうするとスライダー使う意味ができますね．修正します．

2023-06-13 07:04 UTC, penguin-web commented on main.kv
> +                            freq_slider.value = self.text
修正します．

2023-06-13 07:04 UTC, penguin-web commented on main.kv
> +                                    source: "source/left.png"
確かにそうですね．修正します．

2023-06-13 07:05 UTC, penguin-web commented on main.kv
> +                        on_value:
同上

2023-06-13 07:05 UTC, penguin-web commented on main.kv
> +                            on_release:
同上

2023-06-13 07:16 UTC, penguin-web commented on main.kv
> +                                root.check("auto")
修正します．

2023-06-13 07:37 UTC, penguin-web commented on main.kv
> +                                root.check("auto")
なぜですか？

2023-06-13 07:38 UTC, penguin-web commented on main.kv
> +                                on_release:
了解です．修正します．

2023-06-13 07:39 UTC, penguin-web commented on main.kv
> +                    text:"Quit"
了解です

2023-06-13 07:40 UTC, penguin-web commented on main.py
MainWindowクラスの中に入れました．

2023-06-13 07:41 UTC, penguin-web commented on main.kv
> +                                on_press:
修正します．

2023-06-13 08:05 UTC, PlusF commented on main.kv
> +                                root.check("auto")
ごめんなさい，本件は忘れてください．．．以下のようなことを考えていました
ボタンを押した瞬間に「あ，やっぱやめたい」と思ったときに，クリックを保持したままボタンの外までカーソルを持っていくとキャンセルできるとよいかと思ったのですが，kivyの仕様ではon_releaseにしたところでうまくいかなそうです

2023-06-13 08:08 UTC, PlusF commented on main.py
こちらですが，MainWindowクラスに直接関係があるわけではないと思ったので，
単に`MainApp().run()`の前に持ってくるだけでよいかと思いました
いかがでしょう？

2023-06-13 09:21 UTC, merged